# Airflow Env variables.
substitutions:
  _COMPOSER_REGION: asia-south1
  _COMPOSER_ENV_NAME: arflow-hasim
  _ROLLBACK: 'false'
 
  
# Access the id_github file from Secret Manager, and setup SSH
steps:
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    args:
    - -c
    - |
      echo "$$SSH_KEY" >> /root/.ssh/id_rsa
      chmod 400 /root/.ssh/id_rsa
      ssh-keyscan -t rsa github.com > known_hosts.github
      cp known_hosts.github /root/.ssh/known_hosts

# cat known_hosts.github 
    volumes:
    - name: 'ssh'
      path: /root/.ssh
  
# Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args:
    - clone
    - --recurse-submodules
    - git@github.com:Hasimk/cicd-sample.git
    volumes:
    - name: 'ssh'
      path: /root/.ssh

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Clean up older versions
    entrypoint: 'bash'
    args:
     - -c
     - |
       gcloud container images list-tags "gcr.io/fg-dev-host/my-image" \
       --filter="timestamp.date('%Y-%m-%d', Z)<$(date --date='-1 days' +'%Y-%m-%d')" \
       --format="get(digest)" --limit=999999 |  awk '{print "'"gcr.io/fg-dev-host/my-image@"'" $1}' | xargs -n 1 gcloud container images delete --project="fg-dev-host" --force-delete-tags --quiet || exit 0
       
 
#   - name: 'gcr.io/cloud-builders/gcloud'
#     entrypoint: /bin/bash
#     args:
#     - -c
#     - |
#        gcloud artifacts repositories set-cleanup-policy my-image6 \
#        --project=fg-dev-host \
#        --location=us \
#        --policy=policy.json \
    
    
availableSecrets:
    secretManager:
    - versionName: projects/591981386330/secrets/SSH_KEY/versions/latest
      env: 'SSH_KEY'
