substitutions:
  _COMPOSER_REGION: asia-south1
  _COMPOSER_ENV_NAME: arflow-hasim
  
# Access the id_github file from Secret Manager, and setup SSH
steps:
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    args:
    - -c
    - |
      echo "$$SSH_KEY" >> /root/.ssh/id_rsa
      chmod 400 /root/.ssh/id_rsa
      ssh-keyscan -t rsa github.com > known_hosts.github
      cp known_hosts.github /root/.ssh/known_hosts
# cat known_hosts.github 
    volumes:
    - name: 'ssh'
      path: /root/.ssh
  
# Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args:
    - clone
    - --recurse-submodules
    - git@github.com:Hasimk/cicd-sample.git
    volumes:
    - name: 'ssh'
      path: /root/.ssh
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'pull','asia-south1-docker.pkg.dev/fg-dev-host/hasim-airflow/quickstart-image:tag6']
  
   #Set the environment variable for the Docker image
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['composer', 'environments', 'variables', 'create', 'hasim-airflow', '--location=asia-south1', '--environment-variable', 'DOCKER_IMAGE_URI=fg-dev-host/hasim-airflow/quickstart-image:tag6']

   #Update the DAGs in the environment
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['composer', 'environments', 'update', ' hasim-airflow', '--location=asia-south1', '--update-dags']
    
  
  
 ## [End Artifact registry]
  
availableSecrets:
    secretManager:
    - versionName: projects/591981386330/secrets/SSH_KEY/versions/latest
      env: 'SSH_KEY'
