# - Airflow Env variables.
substitutions:
  _COMPOSER_REGION: asia-south1
  _COMPOSER_ENV_NAME: arflow-hasim
  
steps:
  # Step 1: Pull the image from Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', '$_COMPOSER_REGION-docker.pkg.dev/$PROJECT_ID/hasim-airflow/quickstart-image:tag6']

#   # Step 2: Push the image to Cloud Composer
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'gcr.io/$PROJECT_ID/my-image:$BUILD_ID']
#     env: ['CLOUDSDK_COMPOSER_MANAGED_VMs=true']
