steps:
  - name: gcr.io/cloud-builders/git
    args:
      - '-c'
      - |
        echo "$$SSHKEY" > /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        ssh-keyscan github.org > /root/.ssh/known_hosts
    entrypoint: bash
    secretEnv:
      - SSHKEY
    volumes:
      - name: ssh
        path: /root/.ssh
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - '-n'
      - 'git@github.com:Hasimk/cicd-sample.git'
      - .
    volumes:
      - name: ssh
        path: /root/.ssh
  - name: gcr.io/cloud-builders/git
    args:
      - checkout
      - $_TO_SHA
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - |
        for dagfile in $(ls dags/*.py)
        do
        gcloud composer environments storage dags import \
        --environment $$composer-airflow \
        --location asia-south1 \
        --source dags/$$dagfile
        done
    entrypoint: bash
availableSecrets:
  secretManager:
    - versionName: projects/591981386330/secrets/SSHKEY/versions/1
      env: SSHKEY
